### ISSUE TITLE
NavigationItem Extension - Add target audience

### ISSUE THREAD

**Issue by tanczosm** [greenec/EASD-Notifications-Web#5]
Dagon Hunter suggested something that I think is a pretty good idea.   Add an audience target to all Navigation items named "AudienceSlug".   When we set up the links make it possible to target a link to the district, a set of schools (elementary schools), or a particular school.   That way if a student chooses to subscribe to "Easton Area High School", all Navigation Items with an AudienceSlug of "easd_eahs" would show up on the home screen.   "easd" would target all screens, "easd_elem" would target all elementary schools, etc. etc.

Current:
```     public int NavigationItemId { get; set; }
        public int Order { get; set; }  // Order this appears in the list
        public string Title { get; set; }
        public string Type { get; set; }  // "web", "app"
        public string ImageUrl { get; set; }  // file:///filename.jpg or https://etc..
        public string Link { get; set; }
```

Proposed Change:
```
        public int NavigationItemId { get; set; }
        public int Order { get; set; }  // Order this appears in the list
        public string Title { get; set; }
        public string Type { get; set; }  // "web", "app"
        public string AudienceSlug { get; set; } // slug key for intended audience
        public string ImageUrl { get; set; }  // file:///filename.jpg or https://etc..
        public string Link { get; set; }
```

**Comment by greenec** [comment]
Resolved in 16270330f92c6edc560bd4fc58d40e8f36d5f6ac
